import type { GalleryAlbum } from '@/interfaces/content';

/**
 * Staging albums — one album per property/project, ordered as they appear on
 * the gallery page. Images live under /public/images/gallery/staging/<id>/.
 *
 * `label` is the tile title and the carousel caption; `alt` is the accessible
 * description. Add a per-image `desc` to show a line of copy under the caption.
 *
 * CMS-ready: each album maps 1:1 to a document, each image to an asset record.
 *   stagingAlbum (document): { label, slug -> id, images[] }
 *   image (object):          { asset -> src/width/height, label, alt, desc }
 */
export const stagingAlbums: GalleryAlbum[] = [
  {
    id: 'arvada',
    label: 'Arvada',
    images: [
      {
        src: '/images/gallery/staging/arvada/01.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1740,
        height: 1261,
      },
      {
        src: '/images/gallery/staging/arvada/02.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1748,
        height: 1275,
      },
      {
        src: '/images/gallery/staging/arvada/03.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1731,
        height: 1266,
      },
      {
        src: '/images/gallery/staging/arvada/04.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1739,
        height: 1265,
      },
      {
        src: '/images/gallery/staging/arvada/05.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1740,
        height: 1256,
      },
      {
        src: '/images/gallery/staging/arvada/06.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1736,
        height: 1265,
      },
      {
        src: '/images/gallery/staging/arvada/07.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1722,
        height: 1264,
      },
      {
        src: '/images/gallery/staging/arvada/08.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1290,
        height: 914,
      },
      {
        src: '/images/gallery/staging/arvada/09.avif',
        label: 'Arvada',
        alt: 'A professionally staged home in Arvada, Colorado',
        width: 1290,
        height: 895,
      },
    ],
  },
  {
    id: 'castle-rock',
    label: 'Castle Rock',
    images: [
      {
        src: '/images/gallery/staging/castle-rock/01.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1753,
        height: 1268,
      },
      {
        src: '/images/gallery/staging/castle-rock/02.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1727,
        height: 1247,
      },
      {
        src: '/images/gallery/staging/castle-rock/03.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1716,
        height: 1249,
      },
      {
        src: '/images/gallery/staging/castle-rock/04.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1745,
        height: 1266,
      },
      {
        src: '/images/gallery/staging/castle-rock/05.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1734,
        height: 1251,
      },
      {
        src: '/images/gallery/staging/castle-rock/06.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1727,
        height: 1257,
      },
      {
        src: '/images/gallery/staging/castle-rock/07.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1728,
        height: 1252,
      },
      {
        src: '/images/gallery/staging/castle-rock/08.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1744,
        height: 1262,
      },
      {
        src: '/images/gallery/staging/castle-rock/09.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1755,
        height: 1264,
      },
      {
        src: '/images/gallery/staging/castle-rock/10.avif',
        label: 'Castle Rock',
        alt: 'A professionally staged home in Castle Rock, Colorado',
        width: 1759,
        height: 1272,
      },
    ],
  },
  {
    id: 'centennial',
    label: 'Centennial',
    images: [
      {
        src: '/images/gallery/staging/centennial/01.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/02.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/03.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/04.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/05.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/06.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/07.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/08.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/09.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/10.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/11.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/12.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1600,
        height: 1200,
      },
      {
        src: '/images/gallery/staging/centennial/13.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1800,
        height: 1350,
      },
      {
        src: '/images/gallery/staging/centennial/14.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1290,
        height: 933,
      },
      {
        src: '/images/gallery/staging/centennial/15.avif',
        label: 'Centennial',
        alt: 'A professionally staged home in Centennial, Colorado',
        width: 1290,
        height: 928,
      },
    ],
  },
  {
    id: 'denver',
    label: 'Denver',
    images: [
      {
        src: '/images/gallery/staging/denver/01.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1800,
        height: 1158,
      },
      {
        src: '/images/gallery/staging/denver/02.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 830,
      },
      {
        src: '/images/gallery/staging/denver/03.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 828,
      },
      {
        src: '/images/gallery/staging/denver/04.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 765,
      },
      {
        src: '/images/gallery/staging/denver/05.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 747,
      },
      {
        src: '/images/gallery/staging/denver/06.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 792,
      },
      {
        src: '/images/gallery/staging/denver/07.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 785,
      },
      {
        src: '/images/gallery/staging/denver/08.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 783,
      },
      {
        src: '/images/gallery/staging/denver/09.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 782,
      },
      {
        src: '/images/gallery/staging/denver/10.avif',
        label: 'Denver',
        alt: 'A professionally staged home in Denver, Colorado',
        width: 1290,
        height: 770,
      },
    ],
  },
  {
    id: 'greenwood-village',
    label: 'Greenwood Village',
    images: [
      {
        src: '/images/gallery/staging/greenwood-village/01.avif',
        label: 'Greenwood Village',
        alt: 'A professionally staged home in Greenwood Village, Colorado',
        width: 1290,
        height: 920,
      },
      {
        src: '/images/gallery/staging/greenwood-village/02.avif',
        label: 'Greenwood Village',
        alt: 'A professionally staged home in Greenwood Village, Colorado',
        width: 1290,
        height: 947,
      },
    ],
  },
  {
    id: 'longmont',
    label: 'Longmont',
    images: [
      {
        src: '/images/gallery/staging/longmont/01.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1696,
        height: 1135,
      },
      {
        src: '/images/gallery/staging/longmont/02.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1724,
        height: 1161,
      },
      {
        src: '/images/gallery/staging/longmont/03.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1712,
        height: 1136,
      },
      {
        src: '/images/gallery/staging/longmont/04.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1708,
        height: 1145,
      },
      {
        src: '/images/gallery/staging/longmont/05.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1711,
        height: 1236,
      },
      {
        src: '/images/gallery/staging/longmont/06.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1715,
        height: 1274,
      },
      {
        src: '/images/gallery/staging/longmont/07.avif',
        label: 'Longmont',
        alt: 'A professionally staged home in Longmont, Colorado',
        width: 1717,
        height: 1277,
      },
    ],
  },
  {
    id: 'parker',
    label: 'Parker',
    images: [
      {
        src: '/images/gallery/staging/parker/01.avif',
        label: 'Parker',
        alt: 'A professionally staged home in Parker, Colorado',
        width: 1728,
        height: 1254,
      },
      {
        src: '/images/gallery/staging/parker/02.avif',
        label: 'Parker',
        alt: 'A professionally staged home in Parker, Colorado',
        width: 1721,
        height: 1257,
      },
      {
        src: '/images/gallery/staging/parker/03.avif',
        label: 'Parker',
        alt: 'A professionally staged home in Parker, Colorado',
        width: 1723,
        height: 1258,
      },
    ],
  },
  {
    id: 'thornton',
    label: 'Thornton',
    images: [
      {
        src: '/images/gallery/staging/thornton/01.avif',
        label: 'Thornton',
        alt: 'A professionally staged home in Thornton, Colorado',
        width: 1715,
        height: 1250,
      },
      {
        src: '/images/gallery/staging/thornton/02.avif',
        label: 'Thornton',
        alt: 'A professionally staged home in Thornton, Colorado',
        width: 1738,
        height: 1253,
      },
    ],
  },
  {
    id: 'owner-occupied',
    label: 'Owner Occupied',
    images: [
      {
        src: '/images/gallery/staging/owner-occupied/01.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1790,
        height: 1147,
      },
      {
        src: '/images/gallery/staging/owner-occupied/02.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1791,
        height: 1154,
      },
      {
        src: '/images/gallery/staging/owner-occupied/03.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1782,
        height: 1144,
      },
      {
        src: '/images/gallery/staging/owner-occupied/04.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1747,
        height: 1236,
      },
      {
        src: '/images/gallery/staging/owner-occupied/05.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1741,
        height: 1238,
      },
      {
        src: '/images/gallery/staging/owner-occupied/06.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1732,
        height: 1275,
      },
      {
        src: '/images/gallery/staging/owner-occupied/07.avif',
        label: 'Owner Occupied',
        alt: 'An occupied home styled for sale with the owner’s furniture and our inventory',
        width: 1731,
        height: 1265,
      },
    ],
  },
  {
    id: 'design',
    label: 'Design',
    images: [
      {
        src: '/images/gallery/staging/design/01.avif',
        label: 'Design',
        alt: 'An interior design project by Blooming Staging and Design',
        width: 1290,
        height: 809,
      },
      {
        src: '/images/gallery/staging/design/02.avif',
        label: 'Design',
        alt: 'An interior design project by Blooming Staging and Design',
        width: 1290,
        height: 825,
      },
      {
        src: '/images/gallery/staging/design/03.avif',
        label: 'Design',
        alt: 'An interior design project by Blooming Staging and Design',
        width: 1290,
        height: 811,
      },
      {
        src: '/images/gallery/staging/design/04.avif',
        label: 'Design',
        alt: 'An interior design project by Blooming Staging and Design',
        width: 1290,
        height: 1908,
      },
      {
        src: '/images/gallery/staging/design/05.avif',
        label: 'Design',
        alt: 'An interior design project by Blooming Staging and Design',
        width: 1800,
        height: 2400,
      },
    ],
  },
  {
    id: 'behind-the-scenes',
    label: 'Behind the Scenes',
    images: [
      {
        src: '/images/gallery/staging/behind-the-scenes/01.avif',
        label: 'Behind the Scenes',
        alt: 'The Blooming Staging team delivering staging inventory to a project',
        width: 1800,
        height: 2400,
      },
    ],
  },
];
